import type { Metadata } from 'next';
import './globals.css';
import { Geist, Geist_Mono, Montserrat } from 'next/font/google';
import Navbar from './components/Navbar';

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Salon Lepote Goga',
  description: 'Generated by create next app',
  icons: {
    icon: '/salon-goga-logo.png'
  }
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="sr">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/salon-goga-logo.png" type="image/png"/>
      </head>
      <body style={{ fontFamily: 'Montserrat, sans-serif' }}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
